version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
      TZ: Europe/Kiev
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  backup:
    image: postgres:15
    container_name: pg_backup
    depends_on:
      - db
    volumes:
      - ./backups:/backups
    environment:
      - PGPASSWORD=devpass
    entrypoint:
      - bash
      - -c
      - |
        while true; do
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          UUID=$(cat /proc/sys/kernel/random/uuid)
          FILE="/backups/db_${TIMESTAMP}_${UUID}.sql"
          echo "Creating backup: $FILE"
          PGPASSWORD=$POSTGRES_PASSWORD pg_dump -h db -U $POSTGRES_USER $POSTGRES_DB > "$FILE"
          echo "Backup completed: $FILE"
          find /backups -type f -name '*.sql' -mtime +7 -delete
          echo "Old backups deleted"
          sleep 60
        done


  app:
    build: ./app
    container_name: flask_app
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_started


  

volumes:
  db_data:

