name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: nik
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 52198 
          script: |
            cd ~/docker-webapp
            git pull origin main
            docker compose up -d --build
